version: '3.7'

services:
  # app:
  #   depends_on:
  #     - db
  #     - redis
  #   user: bun
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: custom-bun
  #   restart: unless-stopped
  #   working_dir: /usr/src/app
  #   command: sh -c "bun install && bun start"
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./:/usr/src/app
  #   networks:
  #     - ark
  #   environment:
  #     ARK_ADMIN_PASSWORD: ab89EBHAEh5b
  #     ISLAND_RCON_PORT: 27020

  # worker:
  #   depends_on:
  #     - db
  #     - redis
  #     - app
  #   user: bun
  #   image: custom-bun
  #   restart: unless-stopped
  #   working_dir: /usr/src/app
  #   command: sh -c "bun install && bun start:worker"
  #   volumes:
  #     - ./:/usr/src/app
  #   networks:
  #     - ark
  #   environment:
  #     ARK_ADMIN_PASSWORD: ab89EBHAEh5b
  #     ISLAND_RCON_PORT: 27020

  discord:
    user: bun
    image: oven/bun:1.0.4
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "bun install && bun --watch discord/index.discord.ts"
    volumes:
      - ./:/usr/src/app
    networks:
      - ark

  island:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/Saved:/home/arkuser/.steam/steam/steamapps/common
      - ./server/backups:/var/backups/asa-server
      - steam_data:/opt/steamcmd
    ports:
      - 7777:7777/udp
      - 27020:27020/tcp
    networks:
      - ark
    # Increase default grace period to ensure clean shutdown
    stop_grace_period: 45s
    environment:
      # ASA_APPID should only be changed if Wildcard provides a new one
      ASA_APPID: 2430930
      SERVER_MAP: TheIsland_WP
      # SESSION_NAME: 'mytempserverbossman'
      SESSION_NAME: '[US] YINZERS x10 PVP Wipe Quarterly'
      SERVER_PORT: 7777
      MAX_PLAYERS: 70
      SERVER_SHUTDOWN_TIMEOUT: 30

      # Comment to disable password
      # SERVER_PASSWORD: aTempPassword
      ARK_ADMIN_PASSWORD: ab89EBHAEh5b

      # Comment to disable RCON
      # If you disable RCON, the builtin manager won't work
      RCON_PORT: 27020

      # Comment to enable BattlEye
      DISABLE_BATTLEYE: 1

      # Mods: Please provide a comma seperated list of the curse-forge modIDs and uncomment the MODS arg
      # e.g. MODS=931872,931338
      # MODS=

      # Extra arguments
      ARK_EXTRA_OPTS: '?OverrideOfficialDifficulty=5.0?AllowCrateSpawnsOnTopOfStructures=true?AllowFlyingStaminaRecovery=true?ShowFloatingDamageText=true?MaxPersonalTamedDinos=500'
      ARK_EXTRA_DASH_OPTS: '-NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -crossplay -culture=en -ServerRCONOutputTribeLogs -gameplaylogging -servergamelog -servergamelogincludetribelogs'
      EVENT: 'WinterWonderland' # Easter, Arkaeology, ExtinctionChronicles, WinterWonderland, vday, Summer, FearEvolved, TurkeyTrial, birthday, None
    deploy:
      resources:
        limits:
          memory: 12g
    memswap_limit: 16g

  # db:
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: app
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_PASSWORD: password
  #     MYSQL_USER: app
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   healthcheck:
  #     test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
  #     interval: 5s
  #     timeout: 30s
  #     retries: 3
  #     start_period: 5s
  #   volumes:
  #     - /var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - ark

  # redis:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes --requirepass password
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ['CMD', 'redis-cli', 'ping']
  #     interval: 5s
  #     timeout: 30s
  #     retries: 3
  #     start_period: 5s
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - ark

networks:
  ark:
    driver: bridge

volumes:
  steam_data:
