version: '3.7'

services:
  # app:
  #   depends_on:
  #     - db
  #     - redis
  #   user: bun
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: custom-bun
  #   restart: unless-stopped
  #   working_dir: /usr/src/app
  #   command: sh -c "bun install && bun start"
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./:/usr/src/app
  #   networks:
  #     - ark
  #   environment:
  #     ARK_ADMIN_PASSWORD: ab89EBHAEh5b
  #     ISLAND_RCON_PORT: 27020

  # worker:
  #   depends_on:
  #     - db
  #     - redis
  #     - app
  #   user: bun
  #   image: custom-bun
  #   restart: unless-stopped
  #   working_dir: /usr/src/app
  #   command: sh -c "bun install && bun start:worker"
  #   volumes:
  #     - ./:/usr/src/app
  #   networks:
  #     - ark
  #   environment:
  #     ARK_ADMIN_PASSWORD: ab89EBHAEh5b
  #     ISLAND_RCON_PORT: 27020

  discord:
    user: bun
    image: oven/bun:1.0.4
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "bun install && bun --watch discord/index.discord.ts"
    volumes:
      - ./:/usr/src/app
    networks:
      - ark

  island:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/Saved:/opt/steam/steamapps/common/asa-server
      - ./server/backups/the-island:/var/backups/asa-server
      - steam_data:/opt/steamcmd
    ports:
      - 7777:7777/udp
      - 7778:7778/udp
      - 27015:27015/udp
      - 27020:27020/tcp
    networks:
      - ark
    # Increase default grace period to ensure clean shutdown
    stop_grace_period: 30s
    environment:
      SERVER_MAP: TheIsland_WP
      SESSION_NAME: '[US] 10x Fresh Wipe PvP - YINZERS - The Island'
      SERVER_PORT: 7777
      RAW_PORT: 7778
      QUERY_PORT: 27015
      MAX_PLAYERS: 70
      SERVER_SHUTDOWN_TIMEOUT: 30
      ARK_ADMIN_PASSWORD: ab89EBHAEh5b
      CLUSTER: 'yinzers'

      # If you disable RCON, the builtin manager won't work
      RCON_PORT: 27020
      BATTLEYE: 'True'

      # Extra arguments
      ARK_EXTRA_OPTS: '?OverrideOfficialDifficulty=5.0?AllowCrateSpawnsOnTopOfStructures=true?AllowFlyingStaminaRecovery=true?ShowFloatingDamageText=true?MaxPersonalTamedDinos=500'
      ARK_EXTRA_DASH_OPTS: '-NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -crossplay -culture=en -ForceRespawnDinos'
      EVENT: 'Summer' # Easter, Arkaeology, ExtinctionChronicles, WinterWonderland, vday, Summer, FearEvolved, TurkeyTrial, birthday, None
    deploy:
      resources:
        limits:
          memory: 12g
    memswap_limit: 16g

  scorched-earth:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/Saved:/opt/steam/steamapps/common/asa-server
      - ./server/backups/the-center:/var/backups/asa-server
      - steam_data:/opt/steamcmd
    ports:
      - 7779:7779/udp
      - 7780:7780/udp
      - 27017:27017/udp
      - 27022:27022/tcp
    networks:
      - ark
    # Increase default grace period to ensure clean shutdown
    stop_grace_period: 30s
    environment:
      SERVER_MAP: ScorchedEarth_WP
      SESSION_NAME: '[US] 10x Fresh Wipe PvP - YINZERS - Scorched Earth'
      SERVER_PORT: 7779
      RAW_PORT: 7780
      QUERY_PORT: 27017
      MAX_PLAYERS: 70
      SERVER_SHUTDOWN_TIMEOUT: 30
      ARK_ADMIN_PASSWORD: ab89EBHAEh5b
      CLUSTER: 'yinzers'

      # If you disable RCON, the builtin manager won't work
      RCON_PORT: 27022
      BATTLEYE: 'True'

      # Extra arguments
      ARK_EXTRA_OPTS: '?OverrideOfficialDifficulty=5.0?AllowCrateSpawnsOnTopOfStructures=true?AllowFlyingStaminaRecovery=true?ShowFloatingDamageText=true?MaxPersonalTamedDinos=500'
      ARK_EXTRA_DASH_OPTS: '-NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -crossplay -culture=en -ForceRespawnDinos'
      EVENT: 'Summer' # Easter, Arkaeology, ExtinctionChronicles, WinterWonderland, vday, Summer, FearEvolved, TurkeyTrial, birthday, None
    deploy:
      resources:
        limits:
          memory: 12g
    memswap_limit: 16g

  # db:
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: app
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_PASSWORD: password
  #     MYSQL_USER: app
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   healthcheck:
  #     test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
  #     interval: 5s
  #     timeout: 30s
  #     retries: 3
  #     start_period: 5s
  #   volumes:
  #     - /var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - ark

  # redis:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes --requirepass password
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ['CMD', 'redis-cli', 'ping']
  #     interval: 5s
  #     timeout: 30s
  #     retries: 3
  #     start_period: 5s
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - ark

networks:
  ark:
    driver: bridge

volumes:
  steam_data:
