version: '3.7'

services:
  app:
    user: bun
    image: oven/bun:1.0.4
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "bun install && bun start"
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
    networks:
      - ark
    environment:
      ARK_ADMIN_PASSWORD: ab89EBHAEh5b

  # island:
  #   container_name: asa_island
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./ShooterGame:/opt/arkserver/ShooterGame
  #     - /opt/steamcmd
  #   ports:
  #     - 7777:7777/udp
  #   networks:
  #     - ark
  #   environment:
  #     ASA_APPID: 2430930
  #     RCON_PORT: 27020
  #     MAP: TheIsland_WP
  #     SESSION_NAME: '[US] YINZERS x10 PVP Wipe Quarterly'
  #     MAX_PLAYERS: 70
  #     DISABLE_BATTLEYE: 1
  #     # SERVER_PASSWORD:
  #     ARK_ADMIN_PASSWORD: ab89EBHAEh5b
  #     ARK_EXTRA_OPTS: '?OverrideOfficialDifficulty=5.0?AllowCrateSpawnsOnTopOfStructures=true?AllowFlyingStaminaRecovery?ShowFloatingDamageText=true?MaxPersonalTamedDinos=500'
  #     ARK_EXTRA_DASH_OPTS: '-NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -crossplay -culture=en -EnableIdlePlayerKick -ServerRCONOutputTribeLogs -gameplaylogging'
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 12g
  #   memswap_limit: 16g

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: app
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 5s
    ports:
      - 3306:3306
    networks:
      - ark

networks:
  ark:
    driver: bridge
